//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSANPHAM
    {
        public string MASP { get; set; }
        public string MAMAUSP { get; set; }
        public Nullable<int> SLTON { get; set; }
        public Nullable<int> SLBAN { get; set; }
        public string GHICHU { get; set; }
        public byte[] IMG { get; set; }
    
        public virtual MAU MAU { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
