//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBT
    {
        public string MAHDBT { get; set; }
        public Nullable<System.DateTime> NGAYHDBT { get; set; }
        public string MALOAISPBT { get; set; }
        public string MAKHBT { get; set; }
        public string MANVBT { get; set; }
        public Nullable<decimal> SOTIENPHAITRA { get; set; }
        public string TINHTRANG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
