//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONMH
    {
        public string MAHDMH { get; set; }
        public Nullable<System.DateTime> NGAYHDMH { get; set; }
        public string MASPMH { get; set; }
        public string MAKHMH { get; set; }
        public string MANVMH { get; set; }
        public Nullable<bool> LOAITHANHTOAN { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string MAKM { get; set; }
        public Nullable<decimal> SOTIENKM { get; set; }
        public Nullable<decimal> SOTIENPHAITRA { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
