
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FinalProject.Model
{

using System;
    using System.Collections.Generic;
    
public partial class MAU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MAU()
    {

        this.CHITIETSANPHAMs = new HashSet<CHITIETSANPHAM>();

        this.HOADONMHs = new HashSet<HOADONMH>();

    }


    public string MAMAU { get; set; }

    public string TENMAU { get; set; }

    public byte[] IMG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIETSANPHAM> CHITIETSANPHAMs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HOADONMH> HOADONMHs { get; set; }

}

}
